### ISSUE TITLE
There's a wrong file 

### ISSUE THREAD

**Issue by mushroom1224** [pulp-bio/wulpus#14]
In wulpus-main/hw/wulpus_acquisition_pcb/docs/wulpus_acq_pcb_schematics.pdf, R2 should be connected to EN
![image](https://github.com/user-attachments/assets/9f8b4c20-6cb9-4421-9f7f-c2bb3aa84fb4)

**Comment by Sergio5714** [comment]
Thank you for noticing and rfeporting an issue. We further investigated it and found the following:

**Issue:** EN_HV (pin 5 of the U1 DC-DC) connector is probably floating when the MSP430 is not programmed. According to the datasheet of TLV62569, it should not be left floating.
**Potential solution:** There is no need for mounting R2 (EN is controlled by the MCU). But placing a weak pull-down resistor to fix the disabled state (during booting) is necessary.

I am merging this issues in the following issue and closing this one:

https://github.com/pulp-bio/wulpus/issues/17
