### ISSUE TITLE
Power supply spikes exceeding the resistors power rating. Enable pin control of the U1

### ISSUE THREAD

**Issue by Sergio5714** [pulp-bio/wulpus#17]
**Issue:**The power spikes on the supply line VSYS_IN may exceed the power rating of the current measurement resistors R1, R5, R6, R8, R9, R10, R11, R13.
**Potential solution:** Replacing the aforementioned resistors (1 Ohm) with 0.1 Ohm alternatives with the same footprint.

**Issue:** EN_HV (pin 5 of the U1 DC-DC) connector is probably floating when the MSP430 is not programmed. According to the datasheet of TLV62569, it should not be left floating. 
**Potential solution:**  Placing a weak pull-down resistor to fix the disabled state by default.

**Comment by Ethan010722** [comment]
Subject: Issue with EN_HV Pin and Missing 15V Output After Programming MSP430

Hi Sergio,

Thank you for your work on this project. I’ve encountered an issue with the HV board: after programming the MSP430, the 15V high voltage is not generated. I measured the EN_HV pin (Pin 5 of U1, TLV62569), and it shows 0V.

I’ve already tried connecting a 10k pull-up resistor to the EN_HV pin, but it didn’t resolve the issue. Could you advise on what might be causing this problem and how I could fix it?

Looking forward to your guidance!

Best regards,
Ethan

**Comment by Sergio5714** [comment]
We fixed this issue and merged the changes into the dev branch. The changes will be a part of the release 1.2.0.
