### ISSUE TITLE
User guide corrections

### ISSUE THREAD

**Issue by CedricHirschi** [pulp-bio/wulpus#22]
I have come across some points in the user guide where some corrections could be made:

- The USS configuration displayed in Figure 5.2 includes a wrong value: `DC-DC turn on time [us]` should be `100` for the actual time in microseconds, not this legacy ticks number. (Same goes for all USS config GUI screenshots actually)
- Also, I think we should clarify that the channel numbers 1-8 in the schematic correspond to the IDs 0-7 in the GUI as a seperate Note.
  - The TX/RX config for pseudo-B-mode in Table 4.1 for example includes such an error, since the TX channels are specified as `0-8`, which would rather be `0-7`.
  - The waterbath demo also mentions to `please wire the transducer to channel 8`, and although this is mentioned later as `channel number 8 (id = 7)`, this should be uniform in the whole user guide.

These are some more suggestions:
- Could we add more example measurements, even though they may use transducers that are not readily available?
- Add an errata part with the issues we have found up until now? Also manufacturing challenges?

**Comment by Sergio5714** [comment]
We fixed this issue and merged the changes into the dev branch. The changes will be a part of the release 1.2.0.
